name = "marnez-sales-score"
main = "worker/index.js"
compatibility_date = "2026-09-01"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "marnez-sales-score-db"
database_id = "99190a2F-24E4-486D-8C73-65B472E5458E"
